#!/bin/sh -e
#
# ap start
#sudo /home/pi/openpibo-files/system/wifi-ap-sta run

# Amp init
sudo gpio mode 7 out
sudo gpio write 7 1

sudo amixer -c Headphones sset Headphone 75%
sudo play /home/pi/openpibo-files/audio/opening.mp3 reverb &

# network init
sudo python3 /home/pi/openpibo-files/system/booting.py

# run ide
cd /home/pi/openpibo-tools/ide;sudo node main.js &

# run openpibo-tools
cd /home/pi/openpibo-tools/tools;sudo python3 main.py &
exit 0
